export const ADD_CREDENTIALS = 'ADD_CREDENTIALS'
export const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS'
export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS'
export const LOGGING_CREDENTIALS = 'LOGGING_CREDENTIALS'
export const LOGGING_FAILED = 'LOGGING_FAILED'
export const LOG_CREDENTIALS = 'LOG_CREDENTIALS'

export const ADD_CONTACT = 'ADD_CONTACT'
export const GET_CONTACTS = 'GET_CONTACTS'

export const ADD_FRIEND= 'ADD_FRIEND'
export const GET_FRIENDS= 'GET_FRIENDS'
export const SEARCH_FRIEND= 'SEARCH_FRIEND'